# coding: utf-8

"""
    SAP Digital Interconnect LiveLink 365

    The SAP Live Link 365 is a communication platform as a service (CPaaS) that leverages robust delivery technology, SAP’s global relationships, and the power of SAP’s Cloud Platform to provide affordable, scalable, and global messaging solutions for best in class SMS management.  # noqa: E501

    The version of the OpenAPI document: v1.1.0
    Contact: sapdigitalinterconnect@sap.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import app.sap_client
from app.sap_client.models.generate_soft_token_by_key_request import GenerateSoftTokenByKeyRequest  # noqa: E501
from app.sap_client.rest import ApiException


class TestGenerateSoftTokenByKeyRequest(unittest.TestCase):
    """GenerateSoftTokenByKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenerateSoftTokenByKeyRequest(self):
        """Test GenerateSoftTokenByKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = app.sap_client.models.generate_soft_token_by_key_request.GenerateSoftTokenByKeyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
