# coding: utf-8

"""
    SAP Digital Interconnect LiveLink 365

    The SAP Live Link 365 is a communication platform as a service (CPaaS) that leverages robust delivery technology, SAP’s global relationships, and the power of SAP’s Cloud Platform to provide affordable, scalable, and global messaging solutions for best in class SMS management.  # noqa: E501

    The version of the OpenAPI document: v1.1.0
    Contact: sapdigitalinterconnect@sap.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import app.sap_client
from app.sap_client.api.mfa_api import MFAApi  # noqa: E501
from app.sap_client.rest import ApiException


class TestMFAApi(unittest.TestCase):
    """MFAApi unit test stubs"""

    def setUp(self):
        self.api = app.sap_client.api.mfa_api.MFAApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deactivate_soft_token_using_post1(self):
        """Test case for deactivate_soft_token_using_post1

        Deactivate soft token  # noqa: E501
        """
        pass

    def test_generate_token_by_key_using_post1(self):
        """Test case for generate_token_by_key_using_post1

        Generate token by key  # noqa: E501
        """
        pass

    def test_generate_token_using_post1(self):
        """Test case for generate_token_using_post1

        Generates a token  # noqa: E501
        """
        pass

    def test_register_soft_token_using_post1(self):
        """Test case for register_soft_token_using_post1

        Register user and return soft token  # noqa: E501
        """
        pass

    def test_url_authorization_using_post1(self):
        """Test case for url_authorization_using_post1

        urlAuthorization  # noqa: E501
        """
        pass

    def test_validate_soft_token_using_post1(self):
        """Test case for validate_soft_token_using_post1

        Validate soft token  # noqa: E501
        """
        pass

    def test_validate_token_using_post1(self):
        """Test case for validate_token_using_post1

        Validates a token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
