# coding: utf-8

"""
    SAP Digital Interconnect LiveLink 365

    The SAP Live Link 365 is a communication platform as a service (CPaaS) that leverages robust delivery technology, SAP’s global relationships, and the power of SAP’s Cloud Platform to provide affordable, scalable, and global messaging solutions for best in class SMS management.  # noqa: E501

    The version of the OpenAPI document: v1.1.0
    Contact: sapdigitalinterconnect@sap.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import app.sap_client
from app.sap_client.api.authorization_api import AuthorizationApi  # noqa: E501
from app.sap_client.rest import ApiException


class TestAuthorizationApi(unittest.TestCase):
    """AuthorizationApi unit test stubs"""

    def setUp(self):
        self.api = app.sap_client.api.authorization_api.AuthorizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_token_authorization_using_post1(self):
        """Test case for token_authorization_using_post1

        Request Authorization  # noqa: E501
        """
        pass

    def test_validate_using_post1(self):
        """Test case for validate_using_post1

        Validate Authorization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
