# coding: utf-8

"""
    SAP Digital Interconnect LiveLink 365

    The SAP Live Link 365 is a communication platform as a service (CPaaS) that leverages robust delivery technology, SAP’s global relationships, and the power of SAP’s Cloud Platform to provide affordable, scalable, and global messaging solutions for best in class SMS management.  # noqa: E501

    The version of the OpenAPI document: v1.1.0
    Contact: sapdigitalinterconnect@sap.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import app.sap_client
from app.sap_client.api.sms_v__2_0_api import SMSV20Api  # noqa: E501
from app.sap_client.rest import ApiException


class TestSMSV20Api(unittest.TestCase):
    """SMSV20Api unit test stubs"""

    def setUp(self):
        self.api = app.sap_client.api.sms_v__2_0_api.SMSV20Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_mo_using_get1(self):
        """Test case for query_mo_using_get1

        Poll MO (Mobile Originated) Responses  # noqa: E501
        """
        pass

    def test_query_status_using_get1(self):
        """Test case for query_status_using_get1

        Poll SMS delivery statuses  # noqa: E501
        """
        pass

    def test_send_sms_using_post(self):
        """Test case for send_sms_using_post

        Send SMS message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
